dist: bionic
addons:
  apt:
    packages:
      - gcc
      - pkg-config
      - libwebkit2gtk-4.0-dev
      - make
      - wget

language: go
go:
  - "1.13"
env:
  - GO111MODULE=on

cache: pip
install:
  - pip install --user awscli
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/goimports
  - make unshare
script:
  - make onedriver
  - bash .travis_lint.sh
  # we copy the auth_tokens for the test account to and from s3 each build.
  - aws s3 cp s3://fusefs-travis/auth_tokens.json .
  - aws s3 cp s3://fusefs-travis/dmel.fa.gz .
  - gunzip dmel.fa.gz
  - go test -v -covermode=count -coverprofile=coverage.out ./graph
  - go test -c ./offline
  - export TEST_UID=$(id -u)
  - export TEST_GID=$(id -g)
  - sudo ./unshare -n -S $TEST_UID -G $TEST_GID ./offline.test -test.v -test.coverprofile=offline.out
after_script:
  - aws s3 cp auth_tokens.json s3://fusefs-travis/
  - aws s3 cp fusefs_tests.log s3://fusefs-travis/
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out,offline.out -service=travis-ci -repotoken $COVERALLS_TOKEN

notifications:
  email: false
