dist: xenial
addons:
  apt:
    packages:
      - gcc
      - pkg-config
      - libwebkit2gtk-4.0-dev

language: go
go:
  - "1.11"
env:
  - GO111MODULE=on

# we copy the auth_tokens for the test account to and from s3 each build.
cache: pip
install:
  - pip install --user awscli
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - go build
  - aws s3 cp s3://fusefs-travis/auth_tokens.json .
  - aws s3 cp s3://fusefs-travis/dmel.fa.gz .
  - gunzip dmel.fa.gz
  - go test -covermode=count -coverprofile=coverage.out ./logger ./graph
  # travis will timeout if -race is run with -covermode=atomic, so we test separately
  - go test -race
after_script:
  - aws s3 cp auth_tokens.json s3://fusefs-travis/
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

notifications:
  email: false
